import streamlit as st

st.title("About Us - Project")

st.markdown("""
### Project
[Run1_09] PolyPath: A Data-Driven AI Assistant for Informed Course and Career Choices
- **Karthigesan Perumallu** – Project Lead 
- **Jenny Ho** – Project member 

This project aims to support secondary school graduates in making informed choices when selecting a polytechnic diploma course, by consolidating multiple data sources into an intelligent, personalised search and recommendation tool. Currently, course selection is challenging due to fragmented information across different platforms, lack of integrated data on enrolment trends, course structure, career outcomes, and salary prospects.

### Problem Statement
Prospective secondary school graduates enrolling in Singapore polytechnics face difficulties making informed course choices due to fragmented and scattered information across multiple sources such as enrolment statistics, course syllabuses and graduate employment outcomes. Without an integrated platform, students struggle to align their career aspirations with relevant course options and job prospects, while administrators lack a streamlined way to manage and present this data. There is a need for a centralised, interactive system that consolidates diverse data, enables personalised queries based on career goals, job prospects, industry sector or course content for students.

How might we help prospective students for Ngee Ann Polytechnic to make informed course choices by providing personalised career-aligned queries and drawing relevant information from diverse data sources?

Many students in Singapore struggle when choosing polytechnic courses, often feeling overwhelmed by the sheer number of options and limited exposure to how courses align with future careers. This leads to indecision, mismatched expectations, and in some cases, regret or course switching, as reflected in student feedback and forum discussions. With over 20,000 students enrolling in polytechnics each year, the scale of this challenge affects a significant portion of each intake, highlighting the need for better guidance and integrated decision-support tools.

### Proposed Solution

To address the problem highlighted above, we propose the development of an AI-powered course exploration platform leveraging Retrieval-Augmented Generation (RAG). The solution will:
Integrate diverse data sources – including historical enrolment and graduation statistics, course fees, syllabuses, graduate employment survey results, and salary benchmarks – into a unified datastore (e.g., a vector database).

1. Enable intelligent information retrieval – allowing students to submit personalised queries and obtain tailored recommendations generated by a Large Language Model (LLM) such as career goals, job prospects, industry sectors, or course content to better align with students’ aspirations.

2. Provide administrator functionalities – including upload of the datasets described above and built-in data visualisation tools. These visualisations will support analysis of trends such as enrolment and graduation demographics, annual tuition fee information, and employment outcomes (e.g., key survey indicators and median salaries).

This integrated approach will not only guide students in making more informed course selections but also equip administrators with actionable insights to improve programme planning and policy decisions. For the prototype, we have scope the data to use full time diploma courses from one of the local polytechnic (Ngee Ann Polytechnic) to test the solution.

### Impact

Prospective students for Ngee Ann Polytechnic  will no longer need to spend time searching across fragmented sources for course, career, and salary information. Instead, they can access a single intelligent platform that provides personalised insights within minutes.

This reduces the time needed for students to research suitable courses and industry-related information from several hours of manual research to an estimated time of an hour. As a result, students can focus their energy on deeper reflection about their strengths and career goals, rather than struggling to piece together scattered data.

The improved transparency and guidance also empower students to make better-aligned choices, reducing mismatches that often lead to course transfers or dropout risks. Schools, parents, and career coaches benefit too—having reliable, consolidated data at their fingertips to support conversations with students.
Ultimately, this is expected to increase student confidence in their decisions, improve enrolment satisfaction, and support stronger alignment between student course selection, their career aspirations, boosting long-term employability and satisfaction with course selection.

The app will serve as a regular decision-support tool for multiple stakeholders:

- Prospective students - expected to use the app intensively during the 3–6 month course selection window, with repeated sessions as they explore and compare options.

- Parents and career coaches - likely to use it as a reference tool during guidance discussions.

- Policymakers and administrators - using the admin functions periodically to update data (e.g., annually after graduate employment survey release).

On average, we estimate 80% of prospective secondary school students each year will engage with the tool during their decision-making period, while internal stakeholders (e.g., polytechnic reps or counsellors) may use it monthly on average as part of their advisory work.

In the long term, once the app is fully deployed as a self-service tool on the user portal, we estimate that it could directly benefit around 80% of 20,000 users annually. Based on current inquiry trends, this would support approximately 3,000 student inquiries per month. By making the process faster, more accurate, and more transparent, the app will enable a significant portion of our users to make informed decisions through personalized queries tailored to career goals, job prospects, industry sectors, or course content.

The solution delivers substantial productivity savings and aims to reduces the time required for students to research suitable courses and industry-related information from estimated 4 hours to just an hour, resulting in an estimated saving of 48,000 productivity hours annually. Given the small size of the administrators and career coach team, this estimate is conservative and does not account for their time savings.

### Stakeholders & Users

We will conduct further user testing with a representative group of users to gather feedback on the application before presenting the results to senior management. This testing will allow us to collect data on usage, user satisfaction, and productivity gains. The evidence will provide a strong case for fine-tuning, scaling to production, and eventually integrating the application with other polytechnic datasets, enabling cross-institutional insights and more comprehensive guidance for prospective students.

For the immediate phase, the users of the LLM application will include Ngee Ann Polytechnic administrators, career coaches, and a representative sample of prospective students to test and provide feedback.
For the long-term usage, the application is intended to support approximately 80% of the prospective secondary school student cohort, enabling broader access to course exploration, personalised recommendations, and career guidance.

### Lines of Inquiry

1. Prospective students find it difficult to make informed course selection decisions and spent considerable amount of time researching.
2. Providing an AI-powered, personalized course recommendation tool will reduce the time spent, enabling them to focus on deeper reflection about their strengths and career goals and improving students’ confidence and satisfaction in their course choices.
3. Admins and career coaches will save significant time in handling eligibility and advisory inquiries using the tool.

To test our hypotheses or validate our assumptions:
1. User testing with a representative sample – Engage Ngee Ann Poly administrators, career coaches, and a sample cohort of prospective students to interact with the tool and collect qualitative feedback on usability and usefulness.
2. Quantitative metrics – Track improvements in time taken to answer eligibility or advisory queries, usage frequency, and user satisfaction scores.
3. Scenario-based testing – Ask prospective students to complete course selection exercises with and without the tool and measure differences in time spent on decision and confidence of course choice alignment with their career goals.

### Obstacles

- Data integration challenges: Consolidating datasets from multiple sources, especially if formats or structures differ.
- User adoption: Ensuring administrators, career coaches, and students are comfortable using the new tool and fits their use cases.
- Technical constraints: Integrating the app with existing portals or IT infrastructure.
- Maintenance and updates: Keeping the datasets and AI models current over time.
- Funding: Securing sufficient budget for OpenAI credits to run the AI models.

Resources needed to overcome these obstacles:
- Financial resources: Budget for development, testing, hosting the app, periodic updates, and OpenAI credits for AI model usage.
- Human resources: 
    - IT support for integration with existing systems.
    - Data specialists for cleaning, standardizing, and maintaining datasets.
    - Trainers or support staff to guide users through the app.
- Technical resources:
    - Cloud or on-premises infrastructure to host the AI models and datasets.
    - Tools for data preprocessing, monitoring, and security.
    - APIs or connectors for seamless integration with institutional portals.

""")

with st.expander("Disclaimer"):
    
    # Add disclaimer with new lines
    disclaimer = """
    **IMPORTANT NOTICE**: This web application is a prototype developed for educational purposes only. The information provided here is NOT intended for real-world usage and should not be relied upon for making any decisions, especially those related to financial, legal, or healthcare matters.\n\nFurthermore, please be aware that the LLM may generate inaccurate or incorrect information. You assume full responsibility for how you use any generated output.\n\nAlways consult with qualified professionals for accurate and personalized advice. 
   
    """
    st.markdown(disclaimer)
